In [14]:
import numpy as np

In [15]:
#t1 is the coordinate of object to camera
t1 = [[0, 1, 0, 1],
      [1, 0, 0, 10],
      [0, 0, -1, 9],
      [0, 0, 0, 1]]

#t2 is the coordinate of robot base to camera
t2 = [[1, 0, 0, -10],
      [0, -1, 0, 20],
      [0, 0, -1, 10],
      [0, 0, 0, 1]]

#rotation matrix of 90 degree around z-axis of the camera
Rz = [[0, -1, 0, 0],
      [1, 0, 0, 0],
      [0, 0, 1, 0],
      [0, 0, 0, 1]]

#rotation matrix of 90 degree around x-axis of the object
Rx = [[1, 0, 0, 0],
      [0, 0, -1, 0],
      [0, 1, 0, 0],
      [0, 0, 0, 1]]

#translation matrix by 4 unit along the y axis
T  = [[1, 0, 0, 0],
      [0, 1, 0, 4],
      [0, 0, 1, 0],
      [0, 0, 0, 1]]

Question a): After the equipment has been setup and these coordinate systems have been established, someone rotated the camera 90 degree about the z axis of the camera. What is the position and orientation of the camera with respect to the robot’s base coordinate system?

In [16]:
#invert t2 to get the coordinate of the camera with respect to the robot base
t2_invert = np.linalg.inv(t2)
t2_invert

array([[ 1.,  0.,  0., 10.],
       [-0., -1., -0., 20.],
       [-0., -0., -1., 10.],
       [ 0.,  0.,  0.,  1.]])

In [21]:
#the new position and orientation of the camera with respect to the robot base = t2_invert * Rz
rot_cam_to_base = np.matmul(t2_invert,Rz)

for r in rot_cam_to_base:
    print(r)

[ 0. -1.  0. 10.]
[-1.  0.  0. 20.]
[ 0.  0. -1. 10.]
[0. 0. 0. 1.]


Question b) After the rotation happened in a), the object is also rotated by 90 degree about the x axis of the object and translated by 4 units along the rotated y axis. What is the position and orientation of the object with respect to the robot’s base coordinate system? What is the position and orientation of the object with respect to the rotated camera coordinate system?

In [18]:
#the position and orientation of the object with respect to the robot base after rotated
obj_to_base = np.matmul(t2_invert,t1)
rot_obj_to_base = np.matmul(obj_to_base,Rx)
final_obj_to_base = np.matmul(rot_obj_to_base, T)
final_obj_to_base

array([[ 0.,  0., -1., 11.],
       [-1.,  0.,  0., 10.],
       [ 0.,  1.,  0.,  5.],
       [ 0.,  0.,  0.,  1.]])

In [22]:
#the position and orientation of the rotated object with respect to the rotated camera
rot_obj_to_rot_cam = np.matmul(np.linalg.inv(t2), final_obj_to_base)
rot_obj_to_rot_cam

array([[ 0.,  0., -1., 21.],
       [ 1.,  0.,  0., 10.],
       [ 0., -1.,  0.,  5.],
       [ 0.,  0.,  0.,  1.]])